version: '3.9'
services:
  postgres:
    image: postgres:alpine3.20
    container_name: "postgres_container"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: rides_db
      POSTGRES_USER: rides_username
      POSTGRES_PASSWORD: rides_password
    expose:
      - "5432"
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - /data/rides/pg:/var/lib/postgresql/data
      - ../data/init-sql:/docker-entrypoint-initdb.d
    networks:
      local:
  redis:
    image: "redis:alpine"
    container_name: "redis_container"
    ports:
      - "6379:6379"
    volumes:
      - /data/rides/redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      local:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_username
      RABBITMQ_DEFAULT_PASS: rabbit_password
    volumes:
      - /data/rides/rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres:
  redis_data:
    driver: local
  rabbitmq-data:

networks:
  local: