@startuml Start Ride Flow

actor Rider
actor Driver

== Driver Location Tracking ==
Driver->Drivers: Send current location
Drivers->Location: Track driver location
Location->LocationDB: Store driver location

== Rider Location Tracking ==
Rider->Riders: Send current location
Riders->Location: Track rider location
Location->LocationDB: Store rider location

@enduml