@startuml Customer-Driver Allocation Flow

actor Customer
actor Driver

Driver->Service: Set as active
Service->DB: Update as active driver

Customer->Service: Create new trip request
Service->DB: Store new trip

Service->DB: Get nearest available drivers
Service->Cache: Store available driver list
Service->Driver: Notify new trip to drivers

alt Driver accept the trip 
Driver->Service: Accept trip
Service->Customer: Notify matched driver

alt Customer accept the trip
Customer->Service: Accept trip
Service->DB: Update trip data
Service->DB: Set driver as inactive
Service->Cache: Remove available driver list
Service->Driver: Notify to pickup Customer
Service->Customer: Notify to wait for Driver
else Customer reject the trip
Customer->Service: Reject trip
Service->DB: Update trip to be cancelled
Service->Cache: Remove available driver from list
Service->Driver: Notify rejected trip
end

else Driver reject the trip
Driver->Service: Reject trip
Service->Cache: Remove available driver from list
Service->Cache: Get available drivers
alt no drivers available in 10 minutes
Service->DB: Update trip to be cancelled
Service->Customer: Notify "Try Again later."
end
end

@enduml