name: Build Images

on:
  workflow_dispatch:
  workflow_run: 
    workflows: ["Golang Test"]
    types:
      - completed

jobs:
  build-rides:
    name: Build Docker App (Rides)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install dependencies
        run: make tidy-rides
      - name: Build docker images
        run: |
          docker build -f deployments/rides/Dockerfile -t nebengjek/rides:latest .
  push-image-rides:
    name: Push Docker Image (Rides)
    runs-on: ubuntu-latest
    needs: build-rides
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: |
          docker push nebengjek/rides:latest

  build-riders:
    name: Build Docker App (Riders)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install dependencies
        run: make tidy-riders
      - name: Build docker images
        run: |
          docker build -f deployments/riders/Dockerfile -t nebengjek/riders:latest .
  push-image-riders:
    name: Push Docker Image (Riders)
    runs-on: ubuntu-latest
    needs: build-riders
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: |
          docker push nebengjek/riders:latest

  build-drivers:
    name: Build Docker App (Drivers)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install dependencies
        run: make tidy-drivers
      - name: Build docker images
        run: |
          docker build -f deployments/drivers/Dockerfile -t nebengjek/drivers:latest .
  push-image-drivers:
    name: Push Docker Image (Drivers)
    runs-on: ubuntu-latest
    needs: build-drivers
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: |
          docker push nebengjek/drivers:latest
