name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service to be deployed (rides, drivers, riders, location)'
        required: true
        default: 'rides'
      version:
        description: 'Version tag of the application'
        required: false
        default: 'latest'

jobs:
  check-ci:
    name: Check CI Result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check CI
        id: check_status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          previous_run_status=$(gh run list --workflow="Golang Continuous Integration" --limit=1 --json conclusion -q '.[0].conclusion')
          echo "Continuous Integration conclusion: $previous_run_status"

          if [[ "$previous_run_status" != "success" ]]; then
            echo "Continuous Integration did not succeed or unfinished yet. Aborting."
            exit 1
          else
            echo "Continuous Integration succeeded. Continuing..."
          fi
  build-image:
    name: Build and Push Docker Image
    needs: check-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate service name
        run: |
          if [[ "${{ github.event.inputs.service_name }}" != "rides" && \
                "${{ github.event.inputs.service_name }}" != "riders" && \
                "${{ github.event.inputs.service_name }}" != "location" && \
                "${{ github.event.inputs.service_name }}" != "drivers" ]]; then
            echo "Invalid service name specified: ${{ github.event.inputs.service_name }}"
            exit 1
          fi
          echo "Building service: ${{ github.event.inputs.service_name }}"
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install dependencies
        run: make tidy-${{ github.event.inputs.service_name }}
      - name: Build docker image
        run: |
          docker build -f deployments/${{ github.event.inputs.service_name }}/Dockerfile -t ermasavior/nebengjek-${{ github.event.inputs.service_name }}:${{ github.event.inputs.version }} .
      - name: Push docker image
        run: |
          docker push ermasavior/nebengjek-${{ github.event.inputs.service_name }}:${{ github.event.inputs.version }}
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOSTNAME}}
          USERNAME: ${{secrets.SSH_USERNAME}}
          SERVICE_NAME: ${{ github.event.inputs.service_name }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '

            # Now we have got the access of EC2 and we will start the deploy .
            cd /apps &&
            docker compose pull ${SERVICE_NAME}-service &&
            docker compose up -d --no-deps ${SERVICE_NAME}-service
